version: "3.7"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        env: dev
    restart: always
    ports:
      - "3000:3000"
    command: ["npm", "run", "start:dev"]
    links:
      - postgres 
    volumes:
      - .:/app

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_ENABLE_SSL=${DATABASE_ENABLE_SSL}
      - DATABASE_ENABLE_LOGGING=${DATABASE_ENABLE_LOGGING}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5433:5432
    volumes:
        - ./docker/db:/docker-entrypoint-initdb.d/